
### 1. 회원가입
POST {{BASE_URL}}/user
Content-Type: application/json

{
  "userName": "user1",
  "userProfileUrl": ""
}


### 2. 팔로우
POST {{BASE_URL}}/relation/follow
Content-Type: application/json

{
  "userId": "1",
  "targetUserId": "2"
}


### 3. 언팔로우
POST {{BASE_URL}}/relation/unfollow
Content-Type: application/json

{
  "userId": "1",
  "targetUserId": "2"
}


### 4. 팔로워 리스트
GET {{BASE_URL}}/user/2/follower
Content-Type: application/json

